version: '3'

services:
  php-fpm:
    #image: pgporada/php:8.0.13
    image: wsu-base-container:latest
    container_name: wsu-php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./base-site/:/var/www/html/
      - ./php-fpm/:/opt/php-fpm/
    entrypoint: ["/opt/launch.sh", "php-fpm"]
    networks:
      - app-network

  website:
    #image: pgporada/php:8.0.13
    image: wsu-base-container:latest
    container_name: wsu-website
    ports:
      - '3000:3000'
    volumes:
      - ./base-site:/var/www/html
    networks:
      - app-network

  nginx:
    image: ubuntu/nginx:latest
    container_name: wsu-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - ./base-site:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhosts/:/etc/nginx/sites-available/
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wsu-base.rule=Host(`base.local`)"
      - "traefik.http.services.wsu-base.loadbalancer.server.port=80"

  redis:
    image: redis:4.0
    container_name: wsu-redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  traefik:
    image: traefik:2.10
    container_name: wsu-router
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Not used yet because we don't have a database in place (yet)
volumes:
  dbData:
    driver: local
