version: '3'

services:
  php-fpm:
    #image: pgporada/php:8.0.13
    image: wsu-base-container:latest
    container_name: wsu-php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./base-site/:/var/www/html/
      - ./php-fpm/:/opt/php-fpm/
    entrypoint: ["/opt/launch.sh", "php-fpm"]
    networks:
      - app-network

  website:
    #image: pgporada/php:8.0.13
    image: wsu-base-container:latest
    container_name: wsu-website
    ports:
      - '3000:3000'
    volumes:
      - ./base-site:/var/www/html
    networks:
      - app-network

  nginx:
    image: ubuntu/nginx:latest
    container_name: wsu-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - ./base-site:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  redis:
    image: redis:4.0
    container_name: wsu-redis
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Not used yet because we don't have a database in place (yet)
volumes:
  dbData:
    driver: local
